name: PTB KMP Gradle CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle Wrapper
        # https://github.com/gradle/wrapper-validation-action
        # help detect differences in gradle files to prevent homoglyph attack
        uses: gradle/wrapper-validation-action@v1
      - name: Build the project
        run: ./gradlew build